name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y google-chrome-stable
          mkdir -p /usr/local/share/chromedriver
          CHROME_VERSION=$(google-chrome --version | sed 's/[^0-9.]*//g')
          echo "Chrome version: $CHROME_VERSION"
          if [ ! -f /usr/local/share/chromedriver/chromedriver ]; then
            echo "Downloading ChromeDriver..."
            wget "https://chromedriver.storage.googleapis.com/124.0.6367.1/chromedriver_linux64.zip"
            unzip chromedriver_linux64.zip -d /usr/local/share/chromedriver
            chmod +x /usr/local/share/chromedriver/chromedriver
          fi
      - name: Run tests
        run: python tests/test_login.py