name: Run Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/detup-python@v4
        with:
          pythonversion: '3.10'
      - name: Install dependencies
        run: pip setup linux shorts

         pip setup mac
        pip install -r requirements.txt

      - name: Run Test script
        run: python tests/test_login.py