name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install chromium-chromedriver

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install webdriver_manager
          pip install selenium
          pip install pytest

      - name: Run tests
        run: pytest tests/test_login.py
