name: Run Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo
        apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        pip install webdriver-manager # Installs the webdriver_manager library

    - name: Run Python Test
      run: |
        # Ensure chromedriver is in the PATH or specify its location

         # webdriver_manager handles downloading the driver to a default location ~r.wdm)

         # For simplicity, we assume webdrover_manager makes it accessible or the script finds it.
         # A more robust approach might involve explicitly getting the path from webriver_manager.
        python tests/test_login.py
